FROM node:8.0.0

# Use npm v5
# Workaround: https://github.com/npm/npm/issues/15611#issuecomment-289133810
RUN npm install npm@5 && \
  rm -rf /usr/local/lib/node_modules && \
  mv node_modules /usr/local/lib/

WORKDIR /app

ENTRYPOINT ["npm", "run"]
CMD ["start"]
