#!/usr/bin/env bash
function yamlkey_to_value() {
  yamlkey="$1"
  envkey="${yamlkey//./_}"
  varname=$(echo -n "HELM_${ENVIRONMENT}_$envkey" | awk '{print toupper($0)}')
  echo -n "${!varname}"
}

yamlkeys=("$@")

for yamlkey in "${yamlkeys[@]}"; do
  echo "--set \"${yamlkey}=$(yamlkey_to_value "$yamlkey")\""
done

