apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app | quote }}
spec:
  replicas: {{ .Values.scaling.web }}
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: {{ .Values.app | quote }}
      labels:
        app: {{ .Values.app | quote }}
        heritage: binded
        type: web
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Values.app | quote }}
          image: {{ .Values.image | quote }}
          args:
            - "npm"
            - "start"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          env:
            {{- template "env" . }}
