apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    heritage: binded
    type: web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: {{ .Values.app }}
    type: web
